### ISSUE TITLE
Solutions to other Psets

### ISSUE THREAD

**Issue by wwJinkla** [DominickZhang/My-solutions-for-MIT18.S096-2013#1]
Hi! Really appreciate what has been uploaded here. Just wondering if you have solutions to other PSets? I am self studying the materials. Thanks in advance!

**Comment by DominickZhang** [comment]
Hi! Thanks for your attention! Now I am busy with my research paper and preliminary exam. I will upload my solutions after this period, hopefully in this summer. Your comments are welcome!

**Comment by wwJinkla** [comment]
Thanks! Good luck with the exam!
